roles:
  - name: ewc-ansible-role-ipa-client-enroll-1.2
    src: https://github.com/ewcloud/ewc-ansible-role-ipa-client-enroll.git
    version: 1.2.0

  - name: ewc-ansible-role-ipa-client-disenroll-1.1
    src: https://github.com/ewcloud/ewc-ansible-role-ipa-client-disenroll.git
    version: 1.1.0
